# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('content_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('tags', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
